#!/bin/bash 

# check if firefox is already running. 
if pgrep -x "firefox-bin" > /dev/null
then
	echo 'Firefox is already running. Please exit Firefox in order to update it.'
	exit 1
fi

echo "Updating..."

lv=$(./latest_version.pl $(ls firefox*)) 
file_type=$(file $lv)
echo "latest version found: $lv"

echo "unpacking $lv"
if [[ $file_type =~ "bzip2" ]];
then
	bunzip2 $lv || exit $? # should result in a tar file
fi
# only unpack if the directory firefox does not already exist
if [[ $file_type =~ "tar" ]];
then
	tar xf $lv  || exit $? # should result in a directory called 'firefox'
fi

echo 'copying files'
sudo cp -rt /opt/firefox $(pwd)/firefox/* || exit $?
echo 'changing file ownership'
sudo chown -R root:root /opt/firefox/firefox || exit $?

echo 'removing temporary files'
# always run if previous commands were successful
sudo rm -rf $(pwd)/firefox  # remove unpacked firefox
rm -f firefox-* # remove tarballs
echo "Updating completed!"
exit 0
