#!/bin/bash

# check if firefox is already running. 
if pgrep -x "firefox-bin" > /dev/null
then
	echo 'Firefox is already running, cannot update!'
	exit 1
fi

echo "Updating..."
firefox_bz2='firefox-*.tar.bz2'
firefox_tar='firefox-*.tar'

if [ -f $firefox_bz2 ] ; 
then
	echo 'Unpacking firefox...'
	bunzip2 $firefox_bz2 || exit $?
	tar xf $firefox_tar  || exit $?
	echo 'Done!'
else
	echo 'Firefox already unpacked.'
fi

echo 'copying files'
sudo cp -rt /opt/firefox $(pwd)/firefox/* || exit $?
echo 'changing file ownership'
sudo chown -R root:root /opt/firefox/firefox || exit $?

echo 'removing temporary files'
#always run if previous commands were successful
sudo rm -rf $(pwd)/firefox  #remove unpacked firefox
rm -f firefox-* #remove tarballs
echo "Updating completed!"
exit 0
