#!/bin/bash -x

firefox_bz2='firefox-*.tar.bz2'
firefox_tar='firefox-*.tar'


bunzip2 $firefox_bz2
tar xf $firefox_tar 
sudo cp -rt $(pwd) /opt/firefox || exit $?
sudo chown -R root:root /opt/firefox/firefox || exit $?

#always run if previous commands were successful
rm -rf $(pwd)/firefox  #remove unpacked firefox
rm firefox-* #remove tarballs
exit 0
